#!/usr/bin/env python3
"""Generate per-page hero images (desktop 16:9 + mobile portrait, image-matched)
and regenerate all people images with realistic, average-looking, brand-uniform
technicians (ages 25-55, not models)."""
import base64, io, json, os, sys, time, urllib.request
from PIL import Image

KEY = os.environ["GEMINI_API_KEY"]
EP = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key={KEY}"
OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "img")

PHOTO = (" Ultra-realistic professional photograph, natural daylight, sharp focus, photorealistic, true-to-life, "
         "no text, no writing, no captions, no watermark, no logos on signs.")
PEOPLE = (" The technician(s) wear matching PLAIN solid navy-blue work polo shirts — absolutely no text, no writing, "
          "no logo and no graphics anywhere on the clothing. Ordinary, average-looking, believable everyday Canadian "
          "tradespeople with natural realistic faces and normal imperfect features — NOT fashion models, not glamorous, "
          "just regular friendly working people, ages ranging from 25 to 55.")
LEFT = " Compose with the main subject toward the centre-right, leaving the left third calmer and slightly darker for text overlay."

# key -> desktop prompt (16:9). Mobile is generated by recomposing the desktop to portrait.
HEROES = {
 "services": "A friendly average-looking garage door technician in his late 30s kneeling beside a residential garage, using a power drill to repair the door track, North Shore home, bright morning light." + PEOPLE + LEFT + PHOTO,
 "garage-doors": "A stunning modern West Coast home in West Vancouver with a beautiful dark contemporary aluminum garage door with frosted glass accents, golden-hour light, cedar and stone facade, ocean and North Shore mountains behind. No people." + LEFT + PHOTO,
 "openers": "A clean modern white garage door opener motor unit mounted to the ceiling of a tidy residential garage with the belt-drive rail visible, soft daylight from the open door. No people." + LEFT + PHOTO,
 "springs": "Close-up of black galvanized torsion springs mounted on a steel shaft above a residential garage door, crisp mechanical detail, soft garage lighting. No people." + LEFT + PHOTO,
 "strata": "A handsome row of modern West Coast townhomes (a strata complex) in West Vancouver with matching contemporary wood-and-charcoal garage doors, tidy shared driveway and landscaping, blue sky. No people." + LEFT + PHOTO,
 "about": "A friendly family-owned garage door team of three average-looking technicians standing together in a North Shore driveway in front of an open garage, relaxed and approachable, warm daylight." + PEOPLE + LEFT + PHOTO,
 "service-areas": "An elevated scenic view over West Vancouver and the North Shore — forested mountains, the ocean and inlet, leafy residential neighbourhoods below, clear day. No people." + LEFT + PHOTO,
 "reviews": "A beautiful, inviting North Shore family home exterior at golden hour with an elegant modern garage door and warm landscaping lighting. No people." + LEFT + PHOTO,
 "faq": "A tidy, well-organized modern residential garage interior with the sectional door half open letting in bright daylight, clean concrete floor. No people." + LEFT + PHOTO,
 "contact": "A clean white service van parked in a North Shore residential driveway beside a modern garage on a bright day, professional and tidy, blank white van panel with no text or logo. No people." + LEFT + PHOTO,
}

# people content images (cards) -> prompt (aspect 4:3)
PEOPLE_IMGS = {
 "family-team": "A friendly family-owned garage door service team of three average-looking technicians standing in a residential driveway in front of an open garage, smiling, relaxed, a father and two adult sons vibe." + PEOPLE + PHOTO,
 "service-repair": "An average-looking garage door technician kneeling and repairing the bottom bracket and track of a residential garage door with a power drill, focused, tidy suburban garage, daylight." + PEOPLE + PHOTO,
 "service-opener": "An average-looking technician on a small ladder installing a white garage door opener motor unit on a garage ceiling, looking up, clean residential garage." + PEOPLE + PHOTO,
 "service-install": "Two average-looking technicians installing a brand-new sectional garage door panel into the track of a residential garage, teamwork, bright daylight." + PEOPLE + PHOTO,
 "service-maintenance": "An average-looking technician lubricating and inspecting the rollers and hinges of a residential garage door, careful maintenance work, clean garage." + PEOPLE + PHOTO,
}

def call(parts, aspect):
    body = json.dumps({"contents": [{"parts": parts}],
                       "generationConfig": {"responseModalities": ["IMAGE"], "imageConfig": {"aspectRatio": aspect}}}).encode()
    for a in range(4):
        try:
            r = urllib.request.Request(EP, data=body, headers={"Content-Type": "application/json"})
            d = json.load(urllib.request.urlopen(r, timeout=120))
            for p in d["candidates"][0]["content"]["parts"]:
                inl = p.get("inlineData") or p.get("inline_data")
                if inl and inl.get("data"):
                    return base64.b64decode(inl["data"])
            print("  no image in response")
        except Exception as e:
            print("  err", e); time.sleep(2 ** a * 2)
    return None

def save(raw, name, w):
    im = Image.open(io.BytesIO(raw)).convert("RGB")
    if im.width > w:
        im = im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
    p = os.path.join(OUT, name + ".jpg")
    im.save(p, "JPEG", quality=84, optimize=True, progressive=True)
    print(f"  saved {name} {im.size} {os.path.getsize(p)//1024}KB")

def main():
    # heroes: desktop then matched mobile portrait
    for key, prompt in HEROES.items():
        print("HERO", key, "desktop...")
        raw = call([{"text": prompt}], "16:9")
        if not raw: continue
        save(raw, key + "-hero", 1600)
        print("HERO", key, "mobile...")
        b64 = base64.b64encode(raw).decode()
        mprompt = ("Recompose this exact same scene into a TALL VERTICAL 3:4 portrait crop for a mobile banner. "
                   "Keep the same subject, lighting and mood, with the main subject clearly visible and well-composed "
                   "for a portrait frame." + PHOTO)
        raw2 = call([{"text": mprompt}, {"inline_data": {"mime_type": "image/jpeg", "data": b64}}], "3:4")
        if raw2: save(raw2, key + "-hero-mobile", 800)
        time.sleep(1)
    # people content images (4:3)
    for name, prompt in PEOPLE_IMGS.items():
        print("PEOPLE", name)
        raw = call([{"text": prompt}], "4:3")
        if raw: save(raw, name, 1200)
        time.sleep(1)
    print("ALL DONE")

if __name__ == "__main__":
    main()
